### ISSUE TITLE
Is oxidation really a fixed mod?

### ISSUE THREAD

**Issue by edeutsch** [bigbio/proteomics-metadata-standard#120]
In this file:
https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD018117/sdrf.tsv

I am surprised that oxidation is a fixed mod. I think the submitters used a variable mod, and that is more customary. Is is really fixed?

**Comment by ypriverol** [comment]
Fixed https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD018117/sdrf.tsv
