### ISSUE TITLE
Some errors to correct 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#132]
- [x] I think the source names are not correct in  https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD002088/sdrf.tsv
       they differ between fractions

- [x] in  https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD004452/sdrf.tsv
       it also does not contain the enzyme
   
 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD005940/sdrf.tsv does not contain a fraction identifier 

 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD005946/sdrf.tsv replicates are not annotated 
should have a column

 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD006401/sdrf.tsv  source name changes between fractions 

 - [x] in  https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD006675/sdrf.tsv
    source name changes between fractions
 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD008840/sdrf.tsv has associated file uri but not file uri   

 - [x] In  https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD010154/sdrf.tsv entries with  
   AC=MS:1002631;EThcd/ETD are missing the "NT=" 
   
 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD012203/sdrf.tsv seems to contain multiple tabs or whitespaces (I guess there should be "not available" instead)   
   
 - [x] https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PXD000561/sdrf.tsv here also the source name changes between fractions

**Comment by StSchulze** [comment]
In PXD011799 the label column indicates that TMT16plex was used but in the modification parameters TMT6plex is given.

In general, is there any plan to implement a system that tries to guarantee the accuracy of the information provided in the SDRF files? E.g. it could be required to have every SDRF file checked by at least two members of the community before accepting it?
