### ISSUE TITLE
Data without fractions

### ISSUE THREAD

**Issue by foellmelanie** [bigbio/proteomics-metadata-standard#141]
Hi all,

thanks for your efforts to generate better metadata annotations :) 

In the Experiment Design description I am missing an explanation on how to handle unfractionated data. Comment [Fraction Identifier] is included in the templates, therefore I assume one should not delete the column. So far I have decided to enter "1" for every dataset that has no fractions. Would it be more clear to write "not applicable"? 

Maybe you can add one sentence to clarify this in section "3. From Samples to Assay (MSRun)". 

Best,
Melanie

**Comment by ypriverol** [comment]
Hi @foellmelanie : 

Here some ideas. 

> Hi all,
> 
> thanks for your efforts to generate better metadata annotations :)
> 
> In the Experiment Design description I am missing an explanation on how to handle unfractionated data. Comment [Fraction Identifier] is included in the templates, therefore I assume one should not delete the column. So far I have decided to enter "1" for every dataset that has no fractions. Would it be more clear to write "not applicable"?

The best practices should be put `1` and this is what we are encouraging. You took the right way. I will add that to the documentation. 
> 
> Maybe you can add one sentence to clarify this in section "3. From Samples to Assay (MSRun)".
> 
> Best,
> Melanie

**Comment by ypriverol** [comment]
@foellmelanie can you review this PR: https://github.com/bigbio/proteomics-metadata-standard/pull/143 it contains the documentation about the fractions.
