### ISSUE TITLE
source vs individual vs replicate

### ISSUE THREAD

**Issue by foellmelanie** [bigbio/proteomics-metadata-standard#142]
Hi, 

it would be great to add more clarity and/or more examples about the relationship between: 
source name, individual and replicates

I understand individual as individual (human) being. In most (or even all?) cases this will correspond to biological replicate. As long as there are no technical replicates it will also correspond to source name. Or how exactly is source defined? If one tissue is cut into 5 pieces I assume this corresponds to 5 different sources?

Cheers,
Melanie

**Comment by ypriverol** [comment]
This is a TMT dataset 

https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD017710/sdrf-tmt.tsv
