### ISSUE TITLE
How to specify time in [age] column?

### ISSUE THREAD

**Issue by timosachsenberg** [bigbio/proteomics-metadata-standard#146]
e.g. years,  months, days etc.

**Comment by ypriverol** [comment]
@timosachsenberg what do you want to define in age, we normally use `years` not months to days.

**Comment by timosachsenberg** [comment]
in the dataset there are samples from few days old babys.
also few month

**Comment by ypriverol** [comment]
I will try to look for an answer

**Comment by ypriverol** [comment]
@timosachsenberg, This is a proposal from @qinchunyuan https://github.com/bigbio/proteomics-metadata-standard/issues/149

**Comment by timosachsenberg** [comment]
fine with me but maybe ask around a bit more.

**Comment by foellmelanie** [comment]
Hi, 

in my opinion it would be the best to separate values and units. For direct re-use of a dataset and statistical analysis only the value is of interest. 

If value and unit are together it would require an unnecessary separation step.
The format  1Y1M1D would even be more work to first split values and units and then re-calculate  into a single unit to be able to do statistics. 
Also in a few cases the age unit might be very special and would not fit into this general format e.g. "embryonic day" when working with animal embryos. 

My preference would be to specify the unit in the header (age in (embryonic) days).

**Comment by ypriverol** [comment]
Like your comment @foellmelanie . The downside of the two-columns approach is that we need to carry the column of the units with the actual value for every analysis, in addition, order then plays a major role because you can have multiple units for other properties, then you need to relate the age and units after it.

**Comment by foellmelanie** [comment]
@ypriverol I agree that two columns for values and units will get chaotic. Therefore I propose to specify the specific unit only in the header of the column: 
characteristics[age in days] 
The column itself then only contains numeric values that can be immediately used for statistics and the units could also account for very specific units e.g. embryonic days...
