### ISSUE TITLE
About specify time in [age] column 

### ISSUE THREAD

**Issue by daichengxin** [bigbio/proteomics-metadata-standard#149]
In the process of annotating projects, I encountered an expression method of age in https://web.expasy.org/cgi-bin/cellosaurus/search?input=PubMed=22278370, which uses 40Y, 40Y5M, 40Y5M2D to express the age, this may help us specify time

**Comment by daichengxin** [comment]
@ypriverol

**Comment by ypriverol** [comment]
This is Great. @anjaf what do you think?

**Comment by ypriverol** [comment]
Age encoding has been now added to the specification, commit (https://github.com/bigbio/proteomics-metadata-standard/pull/214/commits/27862799b2c9051a859714c3fbff4085ff2c3e76)
