### ISSUE TITLE
How to define site for C-term and N-term modifications

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#16]
The current PR https://github.com/PRIDE-Archive/pride-metadata-standard/pull/15 proposed the `Target Amino acid (TA)` that defines which amino acids will be affected by the modification. The first decision we need to make is, How do we handle C and N term sites. 

In Unimod C and N term sites (amino acid target ) are defined as: C-term and N-term. How is this defined in other tools @StSchulze @trishorts @mvaudel @RalfG @RonBeavis.?

My current proposal is to use: 

`TA=N-term` for example.

**Comment by RalfG** [comment]
As there are modifications that only occur on specific amino acids, only at the N-terminus (Glu->pyro-Glu for instance, if I remember correctly), I think it's best to split up these two properties into two keys. The first would be "amino acid", which could be a specific amino acid, a pattern, or (maybe too as a pattern) any amino acid. The second would be whether or not the modification only occurs at a specific terminus (peptide N/C-term or Protein N/C term).

**Comment by mvaudel** [comment]
Agree with @RalfG. Having the type of target (peptide N-term, protein N-term, peptide C-term, protein C-term, amino acid side-chain) in a mandatory term and amino acid motif as optional term is easier.

**Comment by RalfG** [comment]
This looks good! I guess the only tricky part to add with this method (and we're really going into details here) is which parts of the amino acid are blocked by the modification: side-chain or backbone terminus (NH2- or -COOH). Correct me if I'm wrong on this one, but I guess you could have a variable modification on the first amino acid's side-chain AND a modification on the same amino acids N-terminal NH2-. Or would this combo be denoted as a single modification?

**Comment by ypriverol** [comment]
The current implementation will define as `TA` all possible amino acids. In addition, as suggested by @RalfG we will use the following notations: 

N-term for  NH2- 
C-term for -COOH
.            for side-chain of an N-term
*            for side-chain of a C-Term

**Comment by StSchulze** [comment]
> 
> 
> The current implementation will define as `TA` all possible amino acids. In addition, as suggested by @RalfG we will use the following notations:
> 
> N-term for NH2-
> C-term for -COOH
> `.` for side-chain of an N-term
> `*`for side-chain of a C-Term

To me it's not clear how this differentiates between peptide and protein N/C-term?

So I would agree with the nomenclature of @mvaudel 

I think I also haven't seen any engines, for which one can specify that a side chain is modified but only if the amino acid is at the terminus of a protein/peptide. So I guess that could be a special case that could be omitted for now. Besides that it could be covered by the amino_acid motif/regex, 
e.g. `target="side chain" amino_acid="[-]E"`

**Comment by ypriverol** [comment]
@StSchulze  The current specification defines the position `TP` as Protein N-term, Protein C-term, Anywhere, C-term and N-term. The second property we agree on is Target Amino Acid `TA` that defines the aminoacids affected separated by a comma. Finally, we need to agree in the Target Site `TS` that will be the by the amino_acid motif/regex.

**Comment by StSchulze** [comment]
> 
> 
> @StSchulze The current specification defines the position `TP` as Protein N-term, Protein C-term, Anywhere, C-term and N-term. The second property we agree on is Target Amino Acid `TA` that defines the aminoacids affected separated by a comma. Finally, we need to agree in the Target Site `TS` that will be the by the amino_acid motif/regex.

Sorry, I guess I should have been more specific: I don't see a differentiation between protein and peptide N/C-term for `.` and `*` or if it is specific to the peptide N/C-term, then an equivalent for the protein N/C-term would be missing.

As an aside, I would still be in favor of a more explicit nomenclature ("Peptide N/C-term" instead of "N/C-term"; "amino_acid" instead of "TA", etc.) but that might just be me.

**Comment by ypriverol** [comment]
Some comments: 

> Sorry, I guess I should have been more specific: I don't see a differentiation between protein and peptide N/C-term for . and * or if it is specific to the peptide N/C-term, then an equivalent for the protein N/C-term would be missing.

I try to follow here the UNIMOD definition for the Target position, which are: 

- Any C-term 
- Any N-term 
- Anywhere 
- Protein N-term 
- Protein C-term 

> As an aside, I would still be in favor of a more explicit nomenclature ("Peptide N/C-term" instead of "N/C-term"; "amino_acid" instead of "TA", etc.) but that might just be me.

I really would like to have a more explicit nomenclature but I have the feeling that the tab-delimited representation will be huge. I will create an issue, and after the first proposal get more elaborated, we can vote for more explicit representation.

**Comment by RalfG** [comment]
Just to clarify my proposal, @StSchulze, @ypriverol:

Among the different parameters, we would have:

**TA (target amino acid)**
Defines which specific amino acid is targeted by the modification. Could be:
- One amino acid (side chain): `S`
- Multiple amino acids (side chain): `S,T,Y`
- Any amino acid (side chain): `*`
- N-term amino acid's NH2-: `N-term`
- C-term amino acid's -COOH: `C-term`

**PP (Position on polypeptide)**
Defines where on the peptide/protein the modification occurs. Could be:
- `Anywhere`
- `Protein N-term`
- `Protein C-term`
- `Any N-term`
- `Any C-term`

**Some examples:**
- N-term acetylation: `TA="N-term" PP="Protein N-term"`
- Gln->pyro-Glu: `TA="Q" PP="Any N-term"`
- Phosphorylation: `TA="S,T,Y" PP="Anywhere"`

And then we would also have more complex cases, such as glycosylation, that could use the regex target pattern (`TS`).
