### ISSUE TITLE
MS2 analyzer type and fragmentation energy

### ISSUE THREAD

**Issue by lisavetasol** [bigbio/proteomics-metadata-standard#168]
1. For some Orbitraps it's possible to measure fragments in the ion trap or the Orbitrap. It would be nice to add this information (probably next to the `comment [instrument]`). It may be a bit redundant since there is information about fragment tolerance, but an explicit "MS2 analyser type" column would be a more straightforward characterization of the experiment.
2. There seems to be no way of specifying HCD/CID energy. Since some tools can predict fragmentation spectra for particular energy, this parameter may be helpful with _in silico_ libraries for DIA and different dot product scores.

**Comment by ypriverol** [comment]
> 1. For some Orbitraps it's possible to measure fragments in the ion trap or the Orbitrap. It would be nice to add this information (probably next to the `comment [instrument]`). It may be a bit redundant since there is information about fragment tolerance, but an explicit "MS2 analyzer type" column would be a more straightforward characterization of the experiment.

- @lisavetasol in the ols, you can check under `mass analyzer` all the possible values [mass analyzer](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000451). Those that make sense? Some examples: 

- time-of-flight
- quadrupole
 
> 2. There seems to be no way of specifying HCD/CID energy. Since some tools can predict fragmentation spectra for particular energy, this parameter may be helpful with _in silico_ libraries for DIA and different dot product scores.

In the ols two terms can be use to define energy:

- [collision energy](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000045)
- [activation energy](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000509)

Please, if you think one of these is the appropriate terms let me know. I can add that to the documentation. AS I said before these terms (columns) should be optional (RECOMMENDED).

**Comment by lisavetasol** [comment]
@ypriverol 
1. these `mass analyzer type` values look good, but the issue is that it should be possible to specify different mass analyzer types for MS1 and MS/MS spectra.
2.  I think collision energy is the right term, but there should be also [normalized collision energy ](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000138&viewMode=All&siblings=false) since most of instruments measuring it not explicitly in eV, but in NCE.

**Comment by ypriverol** [comment]
> @ypriverol
> 
> 1. these `mass analyzer type` values look good, but the issue is that it should be possible to specify different mass analyzer types for MS1 and MS/MS spectra.

- You would like two columns?: 

- MS1 mass analyzer type
- MS2 mass analyzer type 

> 2. I think collision energy is the right term, but there should be also [normalized collision energy ](https://www.ebi.ac.uk/ols/ontologies/ms/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMS_1000138&viewMode=All&siblings=false) since most of instruments measuring it not explicitly in eV, but in NCE.

- Lets use `comment[normalized collision energy]`

**Comment by ypriverol** [comment]
@lisavetasol In the normalized collision energy what will be the structure of the value? A Number, a Number with a unit?

**Comment by lisavetasol** [comment]
@ypriverol 
> You would like two columns?:
> MS1 mass analyzer type
> MS2 mass analyzer type

Yep, sounds perfect. 

> Lets use comment[normalized collision energy]

But sometimes collision energy isn't normalized. I think instead of making two comments, it may be better to make one, `[collision energy]` with possible units "NCE" and "eV", so the first one would be for normalized collision energy and the second one for non-normalised one?
And then the structure will be a number and unit.

**Comment by ypriverol** [comment]
New CV Terms in the PRIDE Ontology: 

```python 
id: PRIDE:0000544
name: MS1 mass analyzer
def: "MS1 mass analyzer" []
is_a: MS:1000451 ! mass analyzer
created_by: yperez
creation_date: 2020-03-16T18:01:06Z

[Term]
id: PRIDE:0000545
name: MS2 mass analyzer
def: "MS2 mass analyzer" []
is_a: MS:1000451 ! mass analyzer
``` 
Created

**Comment by lisavetasol** [comment]
Is there a way to specify fragmentation energy in an annotation? Should I just use `comment[collision energy]` and fill it with e.g. '28 NCE' / '20 eV' ?
