### ISSUE TITLE
Error in dataset annotations PXD008222

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#177]
This dataset PXD008222

- [ ] NO Tolerances annotated
- [ ] Technical replicates missing in some files
- [ ] No factor value 

Please fix  these errors.

**Comment by daichengxin** [comment]
#180 .Some raw files should have not  technich replicate and only biological replicate. I did not find them in related materials

**Comment by ypriverol** [comment]
Some files, in the submission, don't need to be added to the submission unless they clearly can be annotated. We know that authors add files to the submission that are not related to the original analysis or are part of a different analysis within the study.

**Comment by ypriverol** [comment]
We should not have `no applicable` or `not available` in the `fraction identifier`, `label` or `technical replicate`

**Comment by daichengxin** [comment]
Thanks a lot.I got it
