### ISSUE TITLE
Regular expression flavor?

### ISSUE THREAD

**Issue by magnuspalmblad** [bigbio/proteomics-metadata-standard#202]
The PTM and enzyme specifications (sensibly) allow regexes. In the example, trypsin is annotated as
`(?⇐[KR])(?!P)`
What flavor or regex format is this, with the ⇐? I suppose the regexes should be consistent.

**Comment by ypriverol** [comment]
@magnuspalmblad we have decided for now to annotate as much as possible the projects using ontology terms for both, the PTMS (UNIMOD) or Enzyme (PSI-MS). We don't have yet any project with fancy Enzymes or PTMs to be annotated. 

Feel free to modify the example and the specification to reflect your comment.

**Comment by mobiusklein** [comment]
That character looks suspiciously like `<=`, which in many regex engines a look-behind assertion, meaning that it will only match the next position if the previous position(s) satisfy that pattern, which makes this a valid definition for Trypsin. Maybe someone pasted from a ligatured source?
