### ISSUE TITLE
Experiment wrong 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#213]
https://github.com/bigbio/proteomics-metadata-standard/blob/f183deb3bb224852e6b8e35fcb9a70cfb7757244/annotated-projects/PXD004683/sdrf.tsv

This experiment is wrong. In TMT experiment each sample should be an independent channel from these labels (https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000515&viewMode=All&siblings=false)

**Comment by XuefeiZ** [comment]
#216

**Comment by levitsky** [comment]
Should this be closed?
