### ISSUE TITLE
Ontology for [ethnic group] and [developmental stage]

### ISSUE THREAD

**Issue by levitsky** [bigbio/proteomics-metadata-standard#220]
Which ontology should I use to look up possible values for `[ethnic group]`? EFO has the [term](http://www.ebi.ac.uk/efo/EFO_0001799) as factor but no descendant nodes for values.

The most representative list I found on OLS is on [ERO](https://www.ebi.ac.uk/ols/ontologies/ero/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FERO_0001972), but that is not a supported ontology.

Similar situation with `[developmental stage]`: EFO term exists but doesn't seem to fit for humans (?), other ontologies have better options.

**Comment by ypriverol** [comment]
@anjaf 

1- The ethnic group ontology term looks wrong in EFO, as pointed out by @levitsky this Cv term  [ancestry category](https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FHANCESTRO_0004&viewMode=All&siblings=false) looks more properly. 

2- @levitsky what are the other options for development stage?  We can added them to the list of supported ontologies.

**Comment by levitsky** [comment]
Ancestry category looks good.

For developmental stage in humans, OLS lists a whole [ontology](https://www.ebi.ac.uk/ols/ontologies/hsapdv), although it has some weirdly specific items; there is also [age group](https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C20587&viewMode=All&siblings=false) in NCI Thesaurus OBO.

**Comment by anjaf** [comment]
Yes, "ethnic group" has been replaced with "ancestry category" in EFO. 
For developmental stages, if EFO doesn't have a suitable term, it's recommended to use a species specific ontology, e.g. PO (plant structure developmental stage, PO_0009012 ), Zebrafish developmental stages ontology (ZFS), FlyBase Developmental Ontology (FBdv), etc. 
We don't have a specific recommendation for a good human developmental stage ontology.

**Comment by ypriverol** [comment]
- [ ] I will replace the `ethnic group` with the `ancestry category`. 
- [ ] I recommend we use for `developmental stage` multiple ontologies: 
       PO (plant structure developmental stage, PO_0009012)
       Zebrafish developmental stages ontology (ZFS)
       FlyBase Developmental Ontology (FBdv)
- For human, I saw that most of the time they added the text of months, years, etc. I think we can recommend using some kind of standard to report time (Year, month, days).

**Comment by levitsky** [comment]
To clarify your suggestion, in terms of mandatory columns **for humans**:

- remove `ethnic group`, add `ancestry category`;
- remove `developmental stage` from _mandatory_ or _recommended_, rely on `age` instead, using the format proposed in #146 or #149.

If that's what you are suggesting, I agree. Also I'm in favor of age format suggested in #149. As mentioned in #146 though, for embryonic samples age may need to be define differently and probably with a different ontology term, but I'm not an expert on that.

**Comment by ypriverol** [comment]
The following PR and commit (https://github.com/bigbio/proteomics-metadata-standard/pull/214/commits/b5cdcbc121fce607fa4e78ea5927e84f2ee38d67) has changed the `ethnic group` -> `ancestry category`

**Comment by ypriverol** [comment]
The `development stage` is now optional. Check the PR commit https://github.com/bigbio/proteomics-metadata-standard/pull/214/commits/e66a7b983b1e383140de33c806183f34aa277d97
