### ISSUE TITLE
Errors in annotations - current submissions 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#228]
@qinchunyuan we have found multiple errors in the annotations of the current submissions, please check: 

{row: 60, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 61, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 62, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 63, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 64, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 65, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 84, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 85, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 86, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 87, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 88, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 89, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 144, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 145, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 146, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 147, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 148, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
{row: 149, column: "characteristics[disease]"}: "osteosarcoma " contains trailing whitespace
- [ ] PXD002395	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age], characteristics[sex] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
- [ ] PXD005940	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD004452	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age], characteristics[sex] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
- [ ] PXD005946	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002087	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type]  -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002080	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD012277	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[disease] -- ERROR
The column characteristics[disease] is not present in the SDRF -- ERROR
{row: 0, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 1, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 2, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 3, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 4, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 5, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 6, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 7, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 8, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 9, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 10, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 11, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 12, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 13, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 14, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 15, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 16, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 17, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 18, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 19, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 20, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 21, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 22, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 23, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 24, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 25, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 26, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 27, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 28, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 29, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 30, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 31, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 32, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 33, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 34, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 35, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 36, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 37, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 38, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 39, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 40, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 41, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 42, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 43, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 44, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 45, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 46, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
{row: 47, column: "characteristics[organism]"}: "mus musculus (mouse)" the term name or title can't be found in the ontology -- ncbitaxon
- [ ] PXD014528	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002081	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002086	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
-[ ] PXD002088	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD017710	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age], characteristics[sex] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
- [ ] PXD000561	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
-[ ] PXD012255	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[organism part], assay name -- ERROR
The column characteristics[organism part] is not present in the SDRF -- ERROR
The column assay name is not present in the SDRF -- ERROR
{row: 0, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 1, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 2, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 3, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 4, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 5, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 6, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 7, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 8, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 9, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 10, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 11, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 12, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 13, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 14, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 15, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 16, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 17, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 18, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 19, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 20, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 21, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 22, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 23, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 24, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 25, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
{row: 26, column: "characteristics[organism]"}: "yeast" the term name or title can't be found in the ontology -- ncbitaxon
-[ ] PXD001819	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
{row: 0, column: "characteristics[age]"}: "no available " contains trailing whitespace
{row: 1, column: "characteristics[age]"}: "no available " contains trailing whitespace
-[ ] PXD018682	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD005355	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
-[ ] PXD011799	Failed validation for human

{row: 0, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 1, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 2, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 3, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 4, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 5, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 6, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 7, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 8, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 9, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 10, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 11, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 12, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 13, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 14, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 15, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 16, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 17, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 18, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
{row: 19, column: "characteristics[organism]"}: "cercopithecus aethiops" the term name or title can't be found in the ontology -- ncbitaxon
-[ ] PXD018241	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD006512	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD008840	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age], characteristics[sex] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
- [ ] PXD008222	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD005354	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD012755	Failed validation for human

The following columns are mandatory and not present in the SDRF: comment[fraction identifier] -- ERROR
The column comment[fraction identifier] is not present in the SDRF -- ERROR
- [ ] PXD005942	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD018581	Failed validation for human

The following columns are mandatory and not present in the SDRF: assay name -- ERROR
The column assay name is not present in the SDRF -- ERROR
- [ ] PXD003133	Failed basic validation

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD000548	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002084	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002619	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
- [ ] PXD018117	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD000547	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002082	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD002049	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type], characteristics[age], characteristics[sex], characteristics[developmental stage] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
The column characteristics[developmental stage] is not present in the SDRF -- ERROR
- [ ] PXD012203	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD006833	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD012431	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[developmental stage] is not present in the SDRF -- ERROR
- [ ] PXD010154	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[developmental stage] is not present in the SDRF -- ERROR
- [ ] PXD000612	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR

- [ ] PXD004682	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type],  characteristics[age], characteristics[sex] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
The column characteristics[age] is not present in the SDRF -- ERROR
The column characteristics[sex] is not present in the SDRF -- ERROR
- [ ] PXD003668	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD004683	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
-[ ] PXD004684	Failed validation for human

The following columns are mandatory and not present in the SDRF: characteristics[cell type] -- ERROR
The column characteristics[cell type] is not present in the SDRF -- ERROR
- [ ] PXD000815	Failed validation for human

**Comment by levitsky** [comment]
It should be noted that some of the required columns are probably going to be made non-mandatory, pending discussion. It doesn't make sense to add "developmental stage" and "ethnicity" now, as the next version of the validator will have a different set of requirements.

**Comment by ypriverol** [comment]
I will delete all the projects reports related to `developmental stage` and `ethnicity`

**Comment by ypriverol** [comment]
> It should be noted that some of the required columns are probably going to be made non-mandatory, pending discussion. It doesn't make sense to add "developmental stage" and "ethnicity" now, as the next version of the validator will have a different set of requirements.

I'm 100% sure that it would be extremely difficult doing post-annotation to find the ethnicity. I think we should make it optional. what do you think @levitsky

**Comment by levitsky** [comment]
Like I said in [before](https://github.com/bigbio/proteomics-metadata-standard/issues/218#issuecomment-626375216), I think we should just allow required fields to be "not available", at least in some cases like post-submission annotation. In my opinion that will be necessary in any case.

As for ethnicity (ancestry category), it will probably often be unknown at submission, too. I don't have a strong opinion whether it should or should not be mandatory.

**Comment by ypriverol** [comment]
@mvaudel do you think we should ask for the ancestry category `ethnicity` for every submission?
