### ISSUE TITLE
Update the CI/CD to validate sdrf files on PRs 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#232]
We need to update the CI/CD in order to be able to validate PRs that contains sdrf changes or additions. 

A prototype of the CI/CD has been built in CircleCI but is not working properly. Related issue: https://github.com/bigbio/proteomics-metadata-standard/issues/222

**Comment by levitsky** [comment]
I have a working Github Actions workflow already. I'm not submitting a PR yet because it doesn't make much sense to run it on every commit and trigger an email to all 17 watchers.

**Comment by ypriverol** [comment]
@levitsky i think is extremely important to have the validation in place. People can put the silence in the messages.

**Comment by ypriverol** [comment]
@levitsky can we do some testing on it. I can't see the Github Actions workflow activated yet.

**Comment by levitsky** [comment]
It should show up after it is first triggered. And that would be by changing anything in the annotated-projects. Do you want me to do a PR just for testing?

I tested the workflow on my fork and locally, it worked for pushes. I didn't try PRs though.

**Comment by ypriverol** [comment]
Yes, please

**Comment by levitsky** [comment]
New workflow was triggered by #234 and failed expectedly.
I'm not sure why CircleCI is still there, though.

**Comment by ypriverol** [comment]
I just stopped the CircleCI part. Hope will work now.
