### ISSUE TITLE
Annotate some DIA and MRM examples

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#246]
It would be great to annotate some DIA and MRM experiments.

**Comment by javizca** [comment]
@davco6 and Ananth have annotated this week 3 experiments. They have different sizes and are human/mouse, so I think they would be perfectly fine to adapt these to the new format. These are PXD005044, PXD005661 and PXD006382. As far as I can see, they can be annotated in the same way as a label free dataset

**Comment by ypriverol** [comment]
> @davco6 and Ananth have annotated this week 3 experiments. They have different sizes and are human/mouse, so I think they would be perfectly fine to adapt these to the new format. These are PXD005044, PXD005661 and PXD006382. As far as I can see, they can be annotated in the same way as a label free dataset

The biology part is the same @javizca but the acquisition part needs to be discussed because some details there are crucial.

**Comment by javizca** [comment]
Yes, I agree. I forgot to mention that they are DIA experiments.
The acquisition part needs to be discussed, but all the relevant information at that level has been gathered for these three datasets, so they are a good starting point. It took some time to find three suitable datasets
