### ISSUE TITLE
Feedback needed

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#262]
Hi @levitsky @pcm32 @foellmelanie @daichengxin @lgatto @anjaf : 

We have been developing a simple web app to help the users to autocomplete Ontology terms and PTMs for the SDRF columns (https://annotator.multiomics.info/). The idea is that a user load an existing dataset and SDRF in their file system and then perform the autocomplete. 

It would be great If you tested and gave us feedback about the tool.

**Comment by levitsky** [comment]
I was able to load an SDRF file into the system (looks like that's the only thing it can do for now).

It shows a warning about empty lines at the end of the file, although there are none.

Editing and auto-completion seem to work. Perhaps it could be useful to highlight values that are not found in the corresponding ontology. I was thinking about adding this in the Python validator as well.

Submitting or saving the table doesn't seem to do anything now, but I guess that's expected.

Also, it looks like the format is not checked very strictly. Even a FASTA file is good enough and is displayed as a table somehow.
