### ISSUE TITLE
biological replicate should be a comment or a characteristics

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#267]
@levitsky @anjaf @daichengxin : 

While technical replicate is annotated always as a comment, the biological replicate is annotated sometimes as comment other as characteristics. See example here https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD000288/sdrf.tsv

I think it should be a characteristic rather than a comment. Please provide feedback. 

@levitsky when we arrive to a conclusion probably we will need to change the validator.

**Comment by daichengxin** [comment]
I prefer that technical replicate is a [comment] , while biological replicate is a [characteristic] . There are several reasons:
1. Technical replicate refers to the number of times the mass spectrometer is run repeatedly on the same sample, more on the MS run level
2. Individually, biological replicate is more like replication at the sample level . Right ??

**Comment by anjaf** [comment]
Yes, I agree. Everything regarding the sample (including biological replicate) should be characteristics, while attributes regarding the assay are comments.

**Comment by levitsky** [comment]
I agree. Should be `characteristics[biological replicate]`.

What do you want to change in the validator about this? It doesn't know about biological replicates.

**Comment by ypriverol** [comment]
I think is the validator we should check that `biological replicate` is not provided as a comment.
