### ISSUE TITLE
Hackathon for annotation of proteomics experiments with EuBic 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#275]
@levitsky @foellmelanie @qinchunyuan @enriquea : 

We are planning to run a workshop with EuBic for annotation of Proteomics datasets after the ASMS. Here a doodle poll to check availability https://doodle.com/poll/h6349immriu866wu The idea is the following: 

Hackathon proposal: 

- 20 minutes introduction is Slack about the format and specification. 
- 15 minutes of general questions about the file format. 

- Hackathon of annotation, every attendant will do the following: 

- Pick a project of interest from PRIDE database. 
- Create an issue in Github of the type (Project Annotation)
- Do a Fork of the Repository, create a folder in the annotated-projects
- Select the corresponding Template and perform the annotation. 
- Do a PR about the Project and Assign two reviewers 
- PR gets merged   

Ideas ?

**Comment by mvaudel** [comment]
To save time, it would be great if you could send information in advance:
1- Program
2- Introduction slides
3- Link to Github tutorials
4- Example of annotated project(s)

and some todos:
1- Make sure you have a working Github account
2- Pick a project in pride

anything else can be done in advance to maximize the throughput of the time we spend together?

**Comment by ypriverol** [comment]
https://github.com/bigbio/proteomics-metadata-standard/tree/master/additional-documentation/Hackathon-062020
