### ISSUE TITLE
Graphical summary

### ISSUE THREAD

**Issue by mvaudel** [bigbio/proteomics-metadata-standard#299]
Given an annotation file, would it be possible to generate a graphical overview e.g. in the form of a tree? This would help QCing the annotation and give a simple overview when browsing a data set.
![Untitled](https://user-images.githubusercontent.com/11632644/83601772-889b7b80-a571-11ea-82d9-fb5f167e62bd.png)

**Comment by ypriverol** [comment]
@mvaudel good idea. I have not to clue how we can do that in the current python API. @levitsky do you have experience with python DAG generation. ?

**Comment by levitsky** [comment]
Not really, but there are probably tools for that. The algorithm is what seems to be challenging.

We have `factor value` (sometimes) that we can use for top-level grouping, what would be next steps? Looks like we need a universal hierarchy of characteristics and comments the define the grouping order.

**Comment by mvaudel** [comment]
Intuitively the order of the split would be: (1) question asked (2) conditions tested (3) patients/samples (4) analytical partitioning. If we cannot answer this, the user will have a hard time doing it :-)

**Comment by levitsky** [comment]
I think the user may have their own idea about the grouping of files or samples. We can try guessing the structure, but I'm not sure if there is such thing as _the_ graphical representation of annotation.

**Comment by ypriverol** [comment]
It is not a bad idea to generate a Dag from the SDRF. It will be the combinations of columns and values: 

- First level: factor value
- Second Level: Biological replicate 
- Thierd level: Techinical replicates 
- Last level: Fractions

**Comment by daichengxin** [comment]
Regarding First level: factor value, I guess if the study variable is cell line, and there are 62 cell lines, then the first-level node will have 62 branches, right? @ypriverol

**Comment by ypriverol** [comment]
yes
