### ISSUE TITLE
Repeated label column

### ISSUE THREAD

**Issue by levitsky** [bigbio/proteomics-metadata-standard#322]
In [PXD017710](https://github.com/bigbio/proteomics-metadata-standard/blob/a141d6bc225e3df8d35e36f0035307f0c7fadf1d/annotated-projects/PXD017710/sdrf-silac.tsv), we have two `label` columns with different values in each row. What does that mean?

Seems to me that only one label per row makes sense.

**Comment by StSchulze** [comment]
It also has TMT6plex in the modifications columns, which doesn't show up in the label columns

**Comment by foellmelanie** [comment]
Further questions on the dataset: the TMT6-plex modification column has at it's end the Carbamidomethyl modifications (;TA=C;AC=UNIMOD:4;MT=fixed)? I never worked with TMT and iTRAQ but I thought they also label lysines? 

NT=TMT6plex;PP=Any N-term;AC=UNIMOD:737;MT=fixed;TA=C;AC=UNIMOD:4;MT=fixed

**Comment by levitsky** [comment]
> NT=TMT6plex;PP=Any N-term;AC=UNIMOD:737;MT=fixed;TA=C;AC=UNIMOD:4;MT=fixed

This very much looks like two columns stuck together. You can't have repeated keys like that. It should be TMT in one column and Carbamidomethyl in the other.

**Comment by ypriverol** [comment]
I'm checking in my machine this error and I can't see the two columns merged

**Comment by ypriverol** [comment]
@levitsky @foellmelanie I have fixed the column in the last PR https://github.com/bigbio/proteomics-metadata-standard/pull/336. 

The second issue is related to How to handle or represent turnover SILAC experiments. In this experiment, the same sample is a label with heavy and light SILAC labels at different times you try to model the amount of protein between both time points.

**Comment by levitsky** [comment]
If I understand correctly what you're saying, "the same sample at different times" should be annotated as two different samples, each with its own label, right?

**Comment by baimingze** [comment]
@levitsky Based on our understanding, the same sample at same time could also been labeled as different SILAC, for example, https://openi.nlm.nih.gov/imgs/512/365/4309511/PMC4309511_pmic0015-0374-f1.png?keywords=escc .

So we thought two "label" column are needed for this situation.

**Comment by levitsky** [comment]
I'm not an expert but it looks like you're right, in such a case a repeated column may be the right way to annotate the sample.

I'm not so sure about the particular data set that I mentioned though: there is still no publication attached to it on PRIDE so I can't check the experiment description, but the metadata has TMT6Plex and doesn't mention SILAC at all.
