### ISSUE TITLE
Standardization of comment[label]

### ISSUE THREAD

**Issue by StSchulze** [bigbio/proteomics-metadata-standard#327]
There are some problem with the comment[label] column, especially for multiplexed experiments. Some of them are already mentioned in issues (e.g #322) but it might make sense to have a more general discussion about this.

1. In general, multiple labels can be part of the same MS run, but a clear connection between the sample and the label need to be made. Therefore, for each label within one MS run, there should be one distinct row describing this sample.

2. The label needs to be clearly defined (e.g. for SILAC, the ontology term "SILAC heavy" is not sufficient to describe which amino acids have been used. It would be potentially possible to include this information within the "comments[modification parameters]" column (e.g. as in #326 right now) but I think this is not desirable since the label column should be understandable by itself and since the modifications column can reflect search parameters instead of only sample characteristics as well. Therefore, the easiest solution would be clearly defined ontology terms. 
- for TMT and ITRAQ this exists already, but different ontologies (PRIDE or MS) are used in different annotations, which might lead to confusion
- for SILAC, Unimod terms exits (e.g. "Label:13C(6)15N(2)") but that would not necessarily clarify the used labeled amino acid. Could we include new terms for the different amino acids within the PRIDE ontology for this purpose?
- for metabolic labeling using heavy isotopes (e.g. 15N), terms within the MI ontology exist but I'm not sure if that's appropriate to use here or if a new term within the PRIDE ontology should be added as well?

Any thoughts or comments on this are welcome.

**Comment by ypriverol** [comment]
Hi @StSchulze:
 

> There are some problem with the comment[label] column, especially for multiplexed experiments. Some of them are already mentioned in issues (e.g #322) but it might make sense to have a more general discussion about this.
> 
> 1. In general, multiple labels can be part of the same MS run, but a clear connection between the sample and the label needs to be made. Therefore, for each label within one MS run, there should be one distinct row describing this sample.

This is now the case. I think the problem we have with the SILAC example is that this is a turnover experiment them the sample is labeled with two different SILAC heavy and light in two different endpoints. We probably need to create samples for that and I'm trying to fix the annotations.  
 
> 2. The label needs to be clearly defined (e.g. for SILAC, the ontology term "SILAC heavy" is not sufficient to describe which amino acids have been used. It would be potentially possible to include this information within the "comments[modification parameters]" column (e.g. as in #326 right now) but I think this is not desirable since the label column should be understandable by itself and since the modifications column can reflect search parameters instead of only sample characteristics as well. Therefore, the easiest solution would be clearly defined ontology terms.
> 
> * for TMT and ITRAQ this exists already, but different ontologies (PRIDE or MS) are used in different annotations, which might lead to confusion
> * for SILAC, Unimod terms exits (e.g. "Label:13C(6)15N(2)") but that would not necessarily clarify the used labeled amino acid. Could we include new terms for the different amino acids within the PRIDE ontology for this purpose?
> * for metabolic labeling using heavy isotopes (e.g. 15N), terms within the MI ontology exist but I'm not sure if that's appropriate to use here or if a new term within the PRIDE ontology should be added as well?

Totally agreed with this. The intention of the `label` column is not to describe the label, which is to express that some labeling happens. For all the multiplex experiments like SILAC, TMT, I agree we should have an additional column to describe properties of the labeling like target aminoacid or label formula.  

- As you said for the TMT we tried to add more information in the label with the specific TMT. The label is informative for pipelines and simple enough for manual annotation. About the redundancy, we created simple terms in PRIDE ontology removing the word `reagent` that is actually not useful and create terms more compact like `TMT{X}` which is actually the term used by most of the community. In the future, we will move those terms to PSI-MS but PRIDE ontology is quick now for updates. 

- For SILAC experiments we can create something similar, but `Label:13C(6)15N(2)` probably is too much for the users to understand or write that in the label column. A search in UNIMOD for SILAC http://www.unimod.org/modifications_list.php?a=search&value=1&SearchFor=SILAC&SearchOption=Contains&SearchField= shows all the possible `formula` of the reagent. In the property `interim name` UNIMOD manages to put a readable name that users can use in their annotations. 

I propose that we extend the PRIDE ontology with those names and in the synonyms or with the property `is_a:` of the ontology term we specify the UNIMOD relation. More interestingly would be to have those specific terms under heavy or light allowing annotators to annotate the more generic terms. 

> 
> Any thoughts or comments on this are welcome.

**Comment by StSchulze** [comment]
> The intention of the label column is not to describe the label, which is to express that some labeling happens. For all the multiplex experiments like SILAC, TMT, I agree we should have an additional column to describe properties of the labeling like target aminoacid or label formula.

Just to clarify, my proposal would be to describe properties of the labeling sufficiently **within** the comments[label] column, not having multiple columns, because I don't see the benefit of a column that just described that some labeling happens without clearly defining how that labeling looks like.

> About the redundancy, we created simple terms in PRIDE ontology removing the word reagent that is actually not useful and create terms more compact like TMT{X} which is actually the term used by most of the community. In the future, we will move those terms to PSI-MS but PRIDE ontology is quick now for updates.

Sounds good.

> I propose that we extend the PRIDE ontology with those names ...

Here would be my suggestions for SILAC label terms:
* SILAC light
  - SILAC light R: 12C(6)14N(4)
  - SILAC light L: 12C(6)
  - SILAC light K: 12C(6)14N(2)
  - SILAC light P: 12C(5)

* SILAC medium
  - SILAC medium R: 13C(6)14N(4)
  - SILAC medium K: 13C(6)14N(2)

* SILAC heavy
  - SILAC heavy R: 13C(6)15N(4)
  - SILAC heavy L: 13C(6)
  - SILAC heavy K: 13C(6)15N(2)

If we stick to the "Label" term in the PRIDE ontology, the "metabolic label" term should also be extended, e.g. like this:


* metabolic label
  - 15N
  - 13C
  - 18O

**Comment by ypriverol** [comment]
@StSchulze I like the approach. I check the first label `12C(6)14N(4)` in unimod and I can't find the formula http://www.unimod.org/modifications_list.php?orderby=dex%5Fcode%5Fname I just want to make sure that the formula is correct

**Comment by ypriverol** [comment]
@StSchulze PR added here https://github.com/PRIDE-Utilities/pride-ontology/pull/44

**Comment by StSchulze** [comment]
> @StSchulze I like the approach. I check the first label `12C(6)14N(4)` in unimod and I can't find the formula http://www.unimod.org/modifications_list.php?orderby=dex%5Fcode%5Fname I just want to make sure that the formula is correct.

It's not a unimod since it is the light label, i.e. the same monoisotopic mass as the original amino acid. 
I took the amico acid compositions from here: https://www.thermofisher.com/us/en/home/life-science/protein-biology/protein-mass-spectrometry-analysis/protein-quantitation-mass-spectrometry/silac-metabolic-labeling-systems.html?gclid=EAIaIQobChMIjq20lvP56QIVGEmGCh2OYQrmEAAYAiAAEgJW0PD_BwE&s_kwcid=AL!3652!3!268177202634!e!!g!!silac%20amino%20acids&ef_id=EAIaIQobChMIjq20lvP56QIVGEmGCh2OYQrmEAAYAiAAEgJW0PD_BwE:G:s&s_kwcid=AL!3652!3!268177202634!e!!g!!silac%20amino%20acids&cid=bid_pca_msp_r01_co_cp1359_pjt0000_bid00000_0se_gaw_nt_pur_con

**Comment by ypriverol** [comment]
All Silac has been included in the new specification.
