### ISSUE TITLE
Sample preparation 

### ISSUE THREAD

**Issue by lisavetasol** [bigbio/proteomics-metadata-standard#331]
There is a piece of information about sample prep which is still missing in the annotations. As @StSchulze [mentioned ](https://github.com/bigbio/proteomics-metadata-standard/issues/293#issuecomment-641559247) before the alkylation agent should be specified separately. If we do that, the reduction agent should be there as well. Since there are not so many of them, it shouldn't be a problem to add exact reagent names (like IAA or DTT) in the Pride ontology (there are already terms for [alkylation](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000026&viewMode=All&siblings=false) and [reduction ](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000025&viewMode=All&siblings=false)). 

The other information which I think is very important related to the digestion method  (in-gel / in-solution). It was shown many times that they give different results as well as modification profiles. Also it's a mandatory field in [ProteomicsDB ](https://www.proteomicsdb.org/#overview)annotations. It probably fits existing term [Enzymatic digestion](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000024&viewMode=All&siblings=false) in the Pride ontology.

There is also an important step related to the tissue storage procedure (like fresh/frozen/formaline-fixed). It strongly affects the modification rates and could be missed from the original search parameters. And just in general such information would be quite helpful for people who are interested in sample prep optimization. Although I cannot easily find a suitable term in the existing annotations (maybe @anjaf could help with this?). 

@ypriverol Anyway, if everyone agreed, I can do PR with terms for alkylation/reduction agents as well as for digestion methods.

**Comment by anjaf** [comment]
Regarding tissue storage there is "specimen with known storage state" in EFO (https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBI_0001472&viewMode=All&siblings=false) that we use for this purpose. It has controlled vocabulary as child terms, e.g. "frozen specimen", "fresh specimen", etc.

**Comment by lisavetasol** [comment]
@ypriverol, @StSchulze, @levitsky 
Now there should be alkylation and reduction reagents in the Pride ontology. So I propose to add the following columns in sdrf : 
1. `comment [reduction reagent] `
2. `comment [alkylation reagent]`
I think ideally both of them should be mandatory, or at least alkylation reagent. The value 'not available' in the column(s) should fail the annotation check (probably not for already existing annotation thought). 

Since there is a good term for the storage conditions (thanks @anjaf), I propose to add the field `comment [specimen storage state] ` for tissue annotations with possible 'not available' value. 

Also, I'm hesitating about 'in-solution/in-gel digest' term. In my experience, this term implements all sample prep stages (reduction, alkylation and digest), not only digest itself. So it's a bit odd to add this field as a part of 'enzymatic digestion', but in the end, it's a question of the description we provide. What do you think?

**Comment by StSchulze** [comment]
The new Pride ontology terms (reduction/alkylation reagent) are great.
I agree that 'in-solution/in-gel digest' describes rather the whole process of sample prep, so instead of 'enzymatic digestion' it might make more sense to put it into a (new?) category 'sample preparation method' that could encompass all the different sample prep workflows like FASP, S-trap, SP3, in-gel, in-solution, etc.

**Comment by ypriverol** [comment]
@lisavetasol @StSchulze can we close this issue?

**Comment by StSchulze** [comment]
What is the solution for the sample preparation method? Adding vocabulary as part of PRIDE "enzymatic digestions" or adding to e.g. MS:1000831? Or ignoring different sample prep methods?

**Comment by lisavetasol** [comment]
I agree with @StSchulze  - the preparation method makes more sense as a separate term under [Protocol step description additional parameter](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000001&viewMode=All&siblings=false) in the PRIDE ontology. 
@ypriverol I think before closing the issue the specified above columns should be added in sdfr (Readme? validation tool?). Also the question about 'being mandatory' doesn't seem to be agreed?

**Comment by ypriverol** [comment]
Can you add the content to the specification @lisavetasol o can merge the PR. I will suggest to do not make it mandatory becuase if the number of mandatory columns start to growth the annotation process can be delay. We can recommended and throw a warning in the validator @levitsky

**Comment by lisavetasol** [comment]
@ypriverol 
I was gonna add alkylation and reduction reagents in Readme and noticed that there is some confusion with `comment` and `characteristics` specification. For now, alkylation and reduction reagent are comments, but for example 'enrichment method' is `characteristics`, although they are in [the same pride ontology](https://www.ebi.ac.uk/ols/ontologies/pride/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPRIDE_0000001&viewMode=All&siblings=false) and in general relate to the same part of an experiment. There is even more confusion with 'depletion', as [pointed out](https://github.com/bigbio/proteomics-metadata-standard/issues/167#issuecomment-632270064) by @levitsky depletion is a `comment` in Readme, but it's `characteristics` in some annotation. 
I think all these 4 parameters (depletion, enrichment, reduction and alkylation) should be the same - either `comment` or `characteristics`. Although, not sure which one?

**Comment by ypriverol** [comment]
I think all properties related to the sample should be moved to sample characteristics rather than comments. What do you think @StSchulze @jgriss @levitsky @mvaudel

**Comment by StSchulze** [comment]
If "sample" is defined as the organism and condition/state it's in before any sample preparation, then I agree it should be comments. 
And I would add to the list of parameters that should be in the same category: enzyme (cleavage agent details) and label (which are currently comments as well, so that fits).

**Comment by jgriss** [comment]
I agree with @StSchulze 

Everything that's part of the original sample and independent of the actual sample prep should be part of "sample". 

Grouping all sample prep associated properties into one category seems like a very good idea and would increase the readability of the format quite a bit.
