### ISSUE TITLE
Normal / uninfected / healthy samples

### ISSUE THREAD

**Issue by levitsky** [bigbio/proteomics-metadata-standard#344]
I suggest standardizing the way of marking samples from organisms that are not affected by disease. This is rather important because `characteristics[disease]` is a required column.

EFO has a term for this called `uninfected`, but it is not under `disease`, rather `disposition` (ancestor of `disease`). So the approach I used was:

characteristics[disposition] | characteristics[disease]
---|---
uninfected | not applicable

A lot of annotations have "normal" or "healthy" as `characterisics[disease]` instead, which is intuitive, but does not map to an ontology term and is not standardized.

What would be the best way to say "no disease"? @anjaf @ypriverol

**Comment by anjaf** [comment]
In Expression Atlas, we use `normal`, mapped to term PATO_0000461 that is in EFO: https://www.ebi.ac.uk/ols/ontologies/efo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0000461

**Comment by ypriverol** [comment]
@levitsky should we add this to the specification? Looks like @anjaf suggestion is to use `normal`.
