### ISSUE TITLE
Annotation / Visualisation of samples that are measured multiple times

### ISSUE THREAD

**Issue by jgriss** [bigbio/proteomics-metadata-standard#352]
## Goal

Several proteomics experiments measure samples multiple times. This can quickly lead to "bloated" annotation files were certain rows are repeated hundreds of times.

In order to create some kind of visualisation tool we need to capture all / most experimental designs that contain repeated measurements of the same samples.

## Experimental designs

  * Super SILAC: one common reference channel
  * TMT / iTRAQ: common reference channel(s) across runs
  * Fractionation (can be combined with nearly all others)

## Comments

@ypriverol @mlocardpaulet @veitveit

**Comment by jgriss** [comment]
First question: Replicates + Common reference

At the moment, this would look like this

```
source name        raw file        replicate
Patient_1              RAW_1_1         1
Reference            RAW_1_1          1
Patient_1              RAW_1_2           2
Reference            RAW_1_2            2
Patient_1              RAW_1_3           3
Reference            RAW_1_3            3
Patient_1              RAW_1_4           4
Reference            RAW_1_4            4
Patient_2              RAW_2_1           1
Reference            RAW_2_1            1
Patient_2              RAW_2_2           2
Reference            RAW_2_2            2
Patient_2              RAW_2_3           3
Reference            RAW_2_3            3
Patient_2              RAW_2_4           4
Reference            RAW_2_4            4
```

How would this be visualised?

**Comment by veitveit** [comment]
Something like:
```
source name        raw file        replicate
Patient_1             +                  +
Reference            +                  +         
Patient_2              +                  +
Patient_3              +                  +
Patient_4              +                  +
...

```
The user can then expand each sample to see files and replicates

This should be applicable to other scenarios, too, particularly when the merged items have identical metadata. E.g. raw files containing multiplexed samples have the same search parameters.

**Comment by ypriverol** [comment]
This is related to this issue. Pooled samples, where samples are merged all together in a channel. @levitsky can you point me to the issue where we discuss that?

**Comment by levitsky** [comment]
Yes, that would be #223.
