### ISSUE TITLE
Needs consistent column name capitalization

### ISSUE THREAD

**Issue by samesense** [bigbio/proteomics-metadata-standard#354]
https://www.dropbox.com/s/xh1ehqsk42skb6w/Screenshot%202020-06-23%2014.38.16.png

https://github.com/bigbio/proteomics-metadata-standard/blob/master/templates/sdrf-human.tsv
vs
https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD000548/sdrf.tsv

**Comment by ypriverol** [comment]
@samesense the current specification does not force annotators to use Upper or Lower case. SDRF is case insensitive meaning `Characteristics` === `characteristics`. https://github.com/bigbio/proteomics-metadata-standard/blob/master/sample-metadata/README.adoc#21-sdrf-values
