### ISSUE TITLE
We need to improve the examples

### ISSUE THREAD

**Issue by mwalzer** [bigbio/proteomics-metadata-standard#40]
* Is it `Characteristics[data file]` (PXD000612) or `Comment[data file]` (NCI60)?
* Also using 'sample n' for a `Source name` is misleading if there is a `Sample column` (and if there is not, too).
* What keeps us from using/adapting the `Labeled extracts` column?

**Comment by mwalzer** [comment]
If I understood correctly, the `Source name` should comprise all fractions (could we use Extractions from the original sdrf definition?).

**Comment by timosachsenberg** [comment]
Thanks for bringing this up. Had the same problem with one of the examples where it was not clear how to group all fractions corresponding to the same biological replicate.

**Comment by ypriverol** [comment]
@mwalzer thanks for reporting this. Here I have fixed some of the examples https://github.com/bigbio/proteomics-metadata-standard/pull/62
