### ISSUE TITLE
Reanalysis of older datasets, no RAW files

### ISSUE THREAD

**Issue by julianu** [bigbio/proteomics-metadata-standard#402]
Hi,

How should a dataset like https://www.ebi.ac.uk/pride/archive/projects/PXD003953 be annotated, which does not hold any "own" RAW files, but is a reanalysis. The submission PXD003953 does not contain the raw (or in this case WIFF) files anymore, only a merged MGF and mzML.
For this special dataset (and some more of mine) I know exactly where the RAWs are stored in PRIDE, e.g. in https://www.ebi.ac.uk/pride/archive/projects/PXD000793 for the example above.

So I could basically just copy the SDRF file from the (just annotated) PXD000793 and put it in the folder for PXD003953, including the links the FTP URIs of the older submission. All data are obviously exactly the same.

But is this desired? And are FTP URIs from one to another project allowed?
Or should we just somehow mark these submissions as identical regarding the study design to another, already annotated, submission?

**Comment by ypriverol** [comment]
@julianu this is absolutely fine.

**Comment by ypriverol** [comment]
@julianu can I close this issue?

**Comment by julianu** [comment]
Yes, I will add the respective datasets then with links to the older PRIDE uploads.
Thanks.
