### ISSUE TITLE
Request Project Annotation [PXD009623 ]

### ISSUE THREAD

**Issue by kleefischda** [bigbio/proteomics-metadata-standard#407]
- Project Accession: [ PXD009623]
- URL Project: [https://www.ebi.ac.uk/pride/archive/projects/PXD009623 ] 
- PubMed Accession: [ 30207155]

**Comment by ypriverol** [comment]
Dear @kleefischda would you be able to annotate the dataset? It would be great if you can do the annotations and we will support you and respond to questions etc.

**Comment by kleefischda** [comment]
Hello @ypriverol. Thank you for your support. I will do my best to annotate it and hope that no further help is needed. Otherwise I will contact you.
