### ISSUE TITLE
Request Project Annotation [PXD004987]

### ISSUE THREAD

**Issue by BajramIbishi** [bigbio/proteomics-metadata-standard#410]
- Project Accession: [PXD004987]
- URL Project: [https://www.ebi.ac.uk/pride/archive/projects/PXD004987] 
- PubMed Accession: [25938255]

**Comment by ypriverol** [comment]
Hi @BajramIbishi thanks for reporting the project. Are you able to annotate it?. I will be more that happy to review your Pull Request and respond to questions.
