### ISSUE TITLE
PXD004682, PXD004683, PXD004684

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#44]
https://www.ebi.ac.uk/pride/archive/projects/PXD004682
https://www.ebi.ac.uk/pride/archive/projects/PXD004683
https://www.ebi.ac.uk/pride/archive/projects/PXD004684

**Comment by daichengxin** [comment]
#207

**Comment by daichengxin** [comment]
Done all #224
