### ISSUE TITLE
How to annotate the disease term (characteristics) if there is no ontology present

### ISSUE THREAD

**Issue by deeptijk** [bigbio/proteomics-metadata-standard#458]
For example, there are six neuropathological stages designated as Braak/Braak (B/B) stages fro the early and late stages of Alzheimer's disease. But there is no ontology term for them yet. How to annotate this kind of project where ontology term is not defined.

**Comment by ypriverol** [comment]
if not term is present, please use free text. In addition, you can request the terms in the EFO ontology https://github.com/EBISPOT/efo
