### ISSUE TITLE
Other experimental readouts, external identifiers

### ISSUE THREAD

**Issue by mvaudel** [bigbio/proteomics-metadata-standard#46]
A raw file is never acquired alone: experimental designs include other experimental readouts like a QC gel, functional follow-up, or other molecular data (sequencing, metabolites, protein properties characterization). Should these be included as well or do you want to stick to the MS file? If external identifiers are available (eg sequencing or metabolites), it would be extremely useful to have them linked here.

**Comment by ypriverol** [comment]
@mvaudel the current format aims to capture the sample metadata to enable reprocessing. The world of Transcriptomics captures into other files more metadata as protocols, etc which I think is important but after years of submissions, it has been seen that nobody use. From these new features which ones do you think we can translate into columns? Which ones do you think are really relevant for the experimental design? 

For example, the protein properties look more like information of the results?  

Thanks for moving this!!! This is really important.
