### ISSUE TITLE
Misc. issues with some SDRF files

### ISSUE THREAD

**Issue by david-bouyssie** [bigbio/proteomics-metadata-standard#467]
I have encountered minor issues with some files:

- [ ] PXD007555 -> comment[xxx mass tolerance] => written as 5ppm, without a space between value and unit so more complicated to parse

- [ ] PXD010603 -> NM instead of NT in some PTM columns

- [ ] PXD016837 -> this one is weird because when parsing from my HTTP client the first char of the responseText is "?"
maybe an encoding issue?

Other minor points:
* sometimes the MT field is missing so I'm thus assuming a variable PTM
* PTM information are sometimes joined with ";" (without space) and sometimes with "; " (with space)
But this is totally manageable
* Last point in some files I get "not applicable" in comment[fraction identifier] instead of 1

**Comment by levitsky** [comment]
Thanks for reporting! I suggest editing the issue into a checklist (basically just add `[ ]` before every item, so we can work on individual items here.

**Comment by david-bouyssie** [comment]
@levitsky done, however for the "other" section, I left it as is, since I'm not sure these points are real issues, so it should be discussed first.
