### ISSUE TITLE
Provide example for multiplexed and fractionated sample

### ISSUE THREAD

**Issue by timosachsenberg** [bigbio/proteomics-metadata-standard#48]
I think we should give an example of how fractions of the same biological sample are grouped.
Ideally in the context of multiplexed data as this is kind of the most complex example.
Also MSstats e.g., considers e.g. pooled normalization channels and has the concept of mixtures.
Basically we should extend 
https://github.com/bigbio/proteomics-metadata-standard/tree/master/experimental-design#3-from-sample-to-msrun

**Comment by ypriverol** [comment]
@timosachsenberg can you do a proposal based on MSTasts. I don't really understand what means `biological sample are grouped` and how this is different from `the experimental factor` the variable that will be finally evaluated.

**Comment by timosachsenberg** [comment]
MSstats has the concepts of:
Run, Fraction, TechRepMixture, Channel, Condition, BioReplicate and Mixture

where:
Run : is just the filename
Fraction : Fraction identifier (e.g., the fraction number). One technical replicate of one mixture may be fractionated into multiple fractions (1,..,n) to increase the analytical depth.
Channel : Labeling information (TMT6_126, ..., TMT6_131).
Condition : Condition (ex. Healthy, Cancer, Time0). If the channal doesn't have sample, please add 'Empty' under Condition.
Mixture : Mixture of samples labeled with different TMT reagents, which can be analyzed in a single mass spectrometry experiment.
TechRepMixture : Technical replicate of one mixture. One mixture may have multiple technical replicates.
For example, if 'TechRepMixture' = 1, 2 are the two technical replicates of one mixture, then they should have the same 'Mixture' value.
  
One technical replicate of one mixture might e.g. be recorded with multiple fractions.
For example, if 'Fraction' = 1, 2, 3 are three fractions of the first technical replicate of one TMT mixture of biological subjects, then they should have same 'TechRepMixture'  and 'Mixture' value.

BioReplicate : Unique ID for a biological sample.

I think we need to model these in the specification to be able to analyse multiplexed data e.g., with channel swaps etc.

**Comment by timosachsenberg** [comment]
So let's take a look what we have:
Run="Comment [data file]"
Channel=Comment [Label]
Fraction=Comment [Fraction Identifier]
BioReplicate="Source Name"  (why optional in spec?)
Condition="Factor Value[NAME OF THE CONDITION]" (what if conditions span multiple factors?)
Mixture =  Currently not modeled. Absolutely needed to group all fractions together!
TechRepMixture=Currently not modeled. Needed to distinguish Mixtures that contain exactly the same labels and samples

**Comment by ypriverol** [comment]
> So let's take a look what we have:
> 
> * Run="Comment [data file]" 
> * Channel=Comment [Label]
> * Fraction=Comment [Fraction Identifier]

Should we make then **"Mandatory"**

> * BioReplicate="Source Name"  (why optional in spec?)

> * Condition="Factor Value[NAME OF THE CONDITION]" (what if conditions span multiple factors?)

This is really simple, nothing stops you to provide multiple Factor Value[CONDITION 1], Factor Value[CONDITION 2] ... Factor Value[CONDITION n] 

> * Mixture =  Currently not modeled. Absolutely needed to group all fractions together!
> * TechRepMixture=Currently not modeled. Needed to distinguish Mixtures that contain exactly the same labels and samples

Can you elaborate on what are these Mixtures?

**Comment by timosachsenberg** [comment]
I mean what if ONE condition spans multiple factors

mixture: you can have sample 1,2,3,4,5,6 measured in TMT6plex but also as e.g., 6,5,4,3,2,1 (aka channel swap)
If you have multiple fractions you can not distinguish the fractions corresponding to 1,2,3,4,5,6 from the ones corresponding to 6,5,4,3,2,1 except if you have the mixture identifier

**Comment by foellmelanie** [comment]
Hi, 
more examples for multiplexed experiments would be really helpful. 
I also like the idea of adopting MSstats annotations. Ideally in a way that the user can directly recycle the MSstats annotation file to annotate the data for PRIDE upload. 
Best,
Melanie

**Comment by ypriverol** [comment]
@foellmelanie: 

@timosachsenberg is working in an exporter from sdrf to MSstats (https://github.com/bigbio/sdrf-openms).

**Comment by timosachsenberg** [comment]
currently only lfq but multiplexed will come soonish

**Comment by foellmelanie** [comment]
Hi, 
this is fantastic for an easy re-analysis! 
I see a lot of benefit to make the other way around (MSstats to sdrf) also as easy as possible. After spending a lot of time to create the MSstats annotation file it would be really frustrating if one has to do the same work all over again to generate the sdrf file for the submission of the raw data to a public repository...

**Comment by ypriverol** [comment]
@foellmelanie : 

Remember two things: 

- SDRF: Is for easy annotation (manually or automatic) of experimental design. 
- MSstats file: Mass spectrometry file format for statistical analysis. 

Our idea now is to have an easy automatic translation from SDRF -> MStats file format, and guidelines on how to translate MSstats fields into SDRF fields. 

Regards  

> Hi,
> this is fantastic for an easy re-analysis!
> I see a lot of benefit to make the other way around (MSstats to sdrf) also as easy as possible. After spending a lot of time to create the MSstats annotation file it would be really frustrating if one has to do the same work all over again to generate the sdrf file for the submission of the raw data to a public repository...

**Comment by foellmelanie** [comment]
Sounds great. I just wanted to point out that the easier MSstats can be translated into sdrf the better :)
