### ISSUE TITLE
SDRFs that fail to generate mqpar.xml file

### ISSUE THREAD

**Issue by savita-nferx** [bigbio/proteomics-metadata-standard#484]
Annotations that are giving error while generating mqpar file; 
PXD002171
PXD013765
PXD000561

Couple of screen shots of error messages: 
<img width="1012" alt="PXD002171" src="https://user-images.githubusercontent.com/65764831/99874594-41807000-2c0f-11eb-87c8-00e3ffb8b8bb.png">
<img width="1073" alt="PXD013765" src="https://user-images.githubusercontent.com/65764831/99874598-46452400-2c0f-11eb-8f95-37bb1e8bc526.png">
For PXD000561, the error was in the version of UNIMOD used, for one of the modifications, the Accession was missing. 

Thanks, 
Savita

**Comment by daichengxin** [comment]
Hi savita, thank you for your feedback. I have added Missing Field in PXD002171 and other annotations that have similar problems. But it’s OK when testing with PXD013765、PXD000561.  Look at your screenshot, it should be the latest version of the code has not been released yet, I will do. @savita-nferx

**Comment by daichengxin** [comment]
Can you check that your code is up to date? @savita-nferx
