### ISSUE TITLE
Adding Experiment type to the sample metadata

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#50]
I think it would be a good idea to include the `Proteomics Data Acquisition Method` to explain the type of experiment, this term is in the `NCI Thesaurus OBO Edition`  ontology and the terms are: 

- Data-Dependent Acquisition
- Data-Independent Acquisition
- Parallel Reaction Monitoring
- Selected Reaction Monitoring

**Comment by foellmelanie** [comment]
Hi @ypriverol it seems that this was never implemented? Why not? I think it is good and would also help to clarify which experiments are "mass spectrometry imaging", even though MSI is not (yet) part of the suggested ontology.

**Comment by ypriverol** [comment]
Yes, I will push for this idea more.

**Comment by foellmelanie** [comment]
Cool. How can the ontology be updated to include MSI?

**Comment by ypriverol** [comment]
We need to request the term in that ontology.

**Comment by levitsky** [comment]
Would be a great enhancement.

Are there any other experiment types not mentioned?

Also, if we make it required, we'll need to go through the bulk of annotations and add them, although it's probably mostly DDA at this point, and DIA is marked in the file names, I think?
