### ISSUE TITLE
Add Technology Type to each SDRF 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#506]
@daichengxin : 

Can you add to each SDRF in my fork https://github.com/ypriverol/proteomics-metadata-standard the field 

`Technology   Type` with the value: `proteomic profiling   by mass spectrometer`

like the project: PXD000288 https://github.com/ypriverol/proteomics-metadata-standard/blob/master/annotated-projects/PXD000288/PXD000288.sdrf.tsv

**Comment by daichengxin** [comment]
I have added @ypriverol . https://github.com/ypriverol/proteomics-metadata-standard/pull/2

**Comment by levitsky** [comment]
Why is this necessary? Are we adding a completely fixed value to every row in every SDRF-Proteomics file everywhere?

**Comment by ypriverol** [comment]
@levitsky the field is optional, but it is RECOMMENDED for compatibility with Transcriptomics data. EXample https://www.ebi.ac.uk/arrayexpress/files/E-MTAB-9694/E-MTAB-9694.sdrf.txt The `Technology Type` is used to describe the omics technology.
