### ISSUE TITLE
Error CPTAC assay names 

### ISSUE THREAD

**Issue by ypriverol** [bigbio/proteomics-metadata-standard#520]
@rudnickp @daichengxin : 

CPTAC datasets have same `assay name`  for different `data files` which is wrong: 

- [ ] @rudnickp or @daichengxin can you fix that. 
- [ ] @levitsky can we validate that in in the sdrf-pipelines.

**Comment by levitsky** [comment]
Sure, you want to validate that data files and assay names correspond 1-to-1?
I can do that, but if @daichengxin is currently working on validation of column order (https://github.com/bigbio/sdrf-pipelines/issues/69), including assay name, should I wait a bit to avoid problems when merging the changes?
