### ISSUE TITLE
PXD010154 instrument/ontology mismatch in sdrf

### ISSUE THREAD

**Issue by glormph** [bigbio/proteomics-metadata-standard#551]
Hi,
I'm not sure I'm doing this correctly but I recently encountered the SDRF for PXD010154, which contains files from a "Q Exactive Plus" instrument. But the instrument ontology code was MS:1002526, which is for an "Exactive Plus", without a Q. The correct code would I guess be to use MS:1002634.

I don't know where how this data is generated, but wanted to inform in case it's mismatched in code or DB somewhere.

**Comment by ypriverol** [comment]
Tahnks, We will be fix it
