### ISSUE TITLE
Dead URLs for annotated examples

### ISSUE THREAD

**Issue by magnuspalmblad** [bigbio/proteomics-metadata-standard#574]
The Label-free and TMT example URLs do not work (https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD008934/sdrf.tsv and https://raw.githubusercontent.com/bigbio/proteomics-metadata-standard/master/annotated-projects/PMID27251275/sdrf.tsv).

**Comment by ypriverol** [comment]
fixed.
