### ISSUE TITLE
Small correction in PXD001819

### ISSUE THREAD

**Issue by julianu** [bigbio/proteomics-metadata-standard#630]
As described in #629 , the old path "ftp.pride.ebi.ac.uk/pride/data/archive/2015/" and subfolders are no longer accessible, therefore changed in the annotation.

Is this something that might concern other projects as well?

**Comment by fabianegli** [comment]
The deprecated EBI FTP url is widespread in this repository. The query for it currently has 172 hits.

See: https://github.com/bigbio/proteomics-metadata-standard/search?q=ftp.pride.ebi.ac.uk
