### ISSUE TITLE
Group fractions in PXD000561

### ISSUE THREAD

**Issue by timosachsenberg** [bigbio/proteomics-metadata-standard#77]
https://github.com/bigbio/proteomics-metadata-standard/blob/master/annotated-projects/PXD000561/sdrf.tsv

@ypriverol should the sample id be the same for all of its fractions

**Comment by ypriverol** [comment]
The sample id is an identifier used by the annotator to differentiate samples, it is not the same for all fractions.

**Comment by timosachsenberg** [comment]
so how do you find out which fractions belong together in this example?

**Comment by timosachsenberg** [comment]
and how should these be different samples if they are just different fractions? Shouldn't this be the same sample measured in several fractions?

**Comment by ypriverol** [comment]
> so how do you find out which fractions belong together in this example?

This is something we need to model with another variable. The `sample id` is a unique identifier for each ROW.

**Comment by timosachsenberg** [comment]
ok, I see. Thanks for clarifying. Would it make sense to use a different name for the row identifier (instead of "sample X")?
For example, one could call it "quant id" as it represents one quantitative value that gets measured (i.e. it works for label-free as well as for a channel in a multiplexed experiment).

**Comment by ypriverol** [comment]
We can do that but this will be up to the user. I think we need to finally introduce the concept about how we organize the fractions that belong to the same `Biological Sample`

**Comment by timosachsenberg** [comment]
as well as technical replicates and "mixtures" the concept in MSstatsTMT that allows to model if samples are measured in different channels

**Comment by ypriverol** [comment]
This has been included in recent documentation.
