### ISSUE TITLE
Minor refinements in SRDF Spec Document 

### ISSUE THREAD

**Issue by javizca** [bigbio/proteomics-metadata-standard#81]
In the table:

|===
| source id  | comment[data file] | comment[label] | comment[fraction identifier] | comment[technical replicate]
| 1 | 000261_C05_P0001563_A00_B00K_F1_TR1.RAW | label free sample | 1 | 1
| 2 | 000261_C05_P0001563_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2
| 3 | 000261_C05_P0001563_A00_B00K_F1_TR1.RAW | label free sample | 1 | 2
| 4 | 000261_C05_P0001563_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2
|===

As far as I can see here, there should be 4 different raw files the ones that would be needed, at the moment there are only two. Each fraction is normally a different raw file. 

The same would be applicable to the following table in the text

|===
| source id  | comment[data file] | comment[label] | comment[fraction identifier] | comment[technical replicate] | comment[biological replicate]
| 1 | 000261_C05_P0001563_A00_B00K_F1_TR1.RAW | label free sample | 1 | 1 | patient 1
| 2 | 000261_C05_P0001563_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2 | patient 1
| 3 | 000261_C05_P0001563_A00_B00K_F1_TR1.RAW | label free sample | 1 | 2 | patient 1
| 4 | 000261_C05_P0001563_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2 | patient 1
| 5 | 000261_C05_P9999999_A00_B00K_F1_TR1.RAW | label free sample | 1 | 1 | patient 2
| 6 | 000261_C05_P9999999_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2 | patient 2
| 7 | 000261_C05_P9999999_A00_B00K_F1_TR1.RAW | label free sample | 1 | 2 | patient 2
| 8 | 000261_C05_P9999999_A00_B00K_F2_TR2.RAW | label free sample | 2 | 2 | patient 2
|===

**Comment by ypriverol** [comment]
Can you review @qinchunyuan this issue.

**Comment by ypriverol** [comment]
https://github.com/bigbio/proteomics-metadata-standard/pull/97
