### ISSUE TITLE
Suggestions about reporting of modifications

### ISSUE THREAD

**Issue by javizca** [bigbio/proteomics-metadata-standard#84]
As far as I can see, if we want the file to be computer readable, one of these two options MUST take place:
- "Database accession" for modifications is made Mandatory (at the moment is optional).

OR

If 'Database Accession' is still optional, then 'Monoisotopic mass' MUST be Mandatory (at the moment is optional).

This would cover cases like novel modifications with no name (but with a known delta mass).

I am not sure how this can be expressed in terms of cardinality in the table.

Also if 'Database Accession' is made mandatory, then to have the information separately about the 'Target Amino acid' is not so essential.

Finally I would change 'Database accession' to 'Modification accession'. It is much more intuitive.

**Comment by ypriverol** [comment]
> As far as I can see, if we want the file to be computer readable, one of these two options MUST take place:
> 
> * "Database accession" for modifications is made Mandatory (at the moment is optional).
> 
> OR
> 
> If 'Database Accession' is still optional, then 'Monoisotopic mass' MUST be Mandatory (at the moment is optional).
We can make that clear now. I will add this sentence in the document. 
> 
> This would cover cases like novel modifications with no name (but with a known delta mass).
> 
> I am not sure how this can be expressed in terms of cardinality in the table.
> 
> Also if 'Database Accession' is made mandatory, then to have the information separately about the 'Target Amino acid' is not so essential.
> 

This is not clear, for most of the modifications you have multiple sites, you really need to know which amino acids will be affected. 

> Finally I would change 'Database accession' to 'Modification accession'. It is much more intuitive.

Done

**Comment by StSchulze** [comment]
Instead of using the monoisotopic mass as a mandatory addition to custom modifications, I would suggest requiring the chemical formula since that would be less ambiguous.

**Comment by ypriverol** [comment]
Thanks @StSchulze, I actually see the benefit on both, then we can make both mandatory or at least one of then. Can you make a PR with the change
