### ISSUE TITLE
Clarify the reporting of channels for multiplex experiments (e.g. TMT)

### ISSUE THREAD

**Issue by javizca** [bigbio/proteomics-metadata-standard#86]
From what I understand from the spec file, the way to report labels would be to use the column 'comment[label]'. But the only example there is a 'label free sample'.

- For TMT experiments the SDRF uses the PRIDE ontology terms under sample label. Here some examples of TMT channels:

TMT126, TMT127, TMT127C , TMT127N, TMT128 , TMT128C, TMT128N, TMT129, TMT129C, TMT129N, TMT130, TMT130C, TMT130N, TMT131

So, this means that the actual channels are included under 'Label'.

One cleaner way would be to use 'Label' to indicate the overall label (TMT in this case) and a different column comment[channel] for the actual channel.

But in any case this needs to be clarified.

Also an example needs to be added for SILAC, because in this case, the actual channels would be in fact different modifications in Unimod/PSI-MOD.

**Comment by ypriverol** [comment]
I have updated the PRIDE ontology, waiting to be index by OLS. I Will check today with the OLS team.

**Comment by ypriverol** [comment]
Indexing will be happening next week.
