### ISSUE TITLE
Discordance in FTP URL in column 10 in sdrf file (comment[associated file uri])

### ISSUE THREAD

**Issue by mstephania** [bigbio/proteomics-metadata-standard#90]
In annotation of PXD000612 project does not exist for the following samples:

pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep4_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep5_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Control_rep6_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep1_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep2_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep3_pH8.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH11.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH3.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH4.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH5.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH6.raw
pY_EXQ5_KiSh_SA_LabelFree_HeLa_Proteome_Nocodazole_rep4_pH8.raw

and for the rest of the samples the URL is different e.g.:
For 20120309_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_EGF_rep4_FT3.raw
instead of this:
ftp://ftp.pride.ebi.ac.uk/pride/archive/projects/PXD000612/20120309_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_EGF_rep4_FT3.raw
it should be this:
ftp://ftp.pride.ebi.ac.uk/pride/data/archive/2014/08/PXD000612/20120309_EXQ5_KiSh_SA_LabelFree_HeLa_Phospho_EGF_rep4_FT3.raw

**Comment by ypriverol** [comment]
Can you @qinchunyuan review this issue.

**Comment by daichengxin** [comment]
Thanks,This issue has been modified
